### PR TITLE
fix: Unnecesarily loop in the static menu.

### LINKED ISSUE #659: [Bug Report] Unnecessarily loop through the static menu
## Bug report

By default the static menu item `ProductInfo` is hidden, and only changes its visibility if the `isAllowInfoProduct` role attribute is set to true. If this attribute is set to false, it is unnecessary to loop through the list of attributes.

#### Other relevant information
- Your OS: Linux Mint 19.1 Cinnamon x64.
- Web Browser: Mozilla Firefox 85.0.
- Node.js version: 12.20.0.
- adempiere-vue version: 4.3.1.

### PR DESCRIPTION
**Pull request by EdwinBetanc0urt**
## Bug report / Feature
The static menu item is traversed to modify the visibility of the `ProductInfo` item, only if the `isAllowInfoProduct` role attribute is set to true.
fixes https://github.com/adempiere/adempiere-vue/issues/659

#### Other relevant information
- Your OS: Linux Mint 19.1 Cinnamon x64.
- Web Browser: Mozilla Firefox 85.0.
- Node.js version: 12.20.0.
- adempiere-vue version: 4.3.1.

### CODE REVIEW

File: src/router/modules/ADempiere/menu.js [hunk 1]
```diff
@@ -155,15 +155,22 @@ function getRouteFromMenuItem({ menu, roleUuid, organizationUuid }) {
...
+    return staticRoutes
+  }
+
   return staticRoutes.map(route => {
     if (route.path === '/ProductInfo') {
       return {
         ...route,
-        hidden: !permiseRole.isAllowInfoProduct
+        // is hidden by default
+        hidden: false
```
Comment (yamelsenih) [inline src/router/modules/ADempiere/menu.js]: Hi @EdwinBetanc0urt this is for validate for role access, please propose a better solution for keep role access

**Review by yamelsenih — CHANGES_REQUESTED** [review]

File: src/router/modules/ADempiere/menu.js (hunk 1 above)
Comment (EdwinBetanc0urt) [reply src/router/modules/ADempiere/menu.js]: @yamelsenih Suggested changes implemented

**Comment by yamelsenih** [comment]
Great catch
