### PR TITLE
Focus the Field

### LINKED ISSUE #721: [Bug Report]  "Reference number" field error
## Bug report

The following error is that at the moment of making the payment, and having as payment type "Direct Debt" this enables a field called "Reference Number" which is associated with the reference that throws the ticket that throws the point of sale, when typing in that field it only takes one value, the field is inactivated, and it has to be checked again to associate the next value and so on

#### Steps to reproduce

The steps to follow for this case are:

1. Place an order
2.Apply the collection and check the payment rule "Direct Debit"

#### Screenshot or Gif（截图或动态图）

Foco_Campo_N_Referencia

#### Link to minimal reproduction（最小可在线还原demo）

https://demo-ui.erpya.com/

#### Expected behavior
The expected result for this commented error is that when the reference number is associated, it remains within the field to continue transcribing the values ​​that are required.

### PR DESCRIPTION
**Pull request by elsiosanchez**
## Bug report 
Focus the Field
#### Steps to reproduce

1. Add a payment method
2. In the reference field add the reference without losing the focus.

#### Screenshot or Gif

Peek 07-04-2021 14-44

#### Link to minimal reproduction
[https://demo-ui.erpya.com](https://deploy-preview-723--stoic-lamport-68decf.netlify.app/)

#### Other relevant information
- Your OS: Debian 9
- Web Browser: Chrome
- Node.js version: 10.0

#### Issues
Fixes: #721

### CODE REVIEW

**Comment by oscarinak** [comment]
The verification was carried out in the service "https://deploy-preview-723--stoic-lamport-68decf.netlify.app/" where it was observed through a test carried out that the error in the field "Reference N °" was corrected


Verificacion_Campo_Numero_referencia-PDV

File: src/components/RightPanel/index.vue [hunk 1]
```diff
@@ -53,9 +53,9 @@ export default {
       }
     }
   },
-  mounted() {
-    this.insertToBody()
-  },
+  // mounted() {
```
Comment (yamelsenih) [inline src/components/RightPanel/index.vue]: Please remove completely

File: src/components/ADempiere/RightPanel/index.vue [hunk 2]
```diff
@@ -76,9 +76,9 @@ export default {
       }
     }
   },
-  mounted() {
-    this.insertToBody()
-  },
+  // mounted() {
+  //   this.insertToBody()
```
Comment (yamelsenih) [inline src/components/ADempiere/RightPanel/index.vue]: Please remove completely

**Review by yamelsenih — CHANGES_REQUESTED** [review]
