### PR TITLE
Fix Load panel and fields in window

### LINKED ISSUE #1681: [Bug Report] Bug in the window
## Bug report
Bug in the window

Error does not load the panel with the fields. This case only happens with windows since in the process and smart browser it works
#### Steps to reproduce

1. start section
2. there will be any window
3. notice the bug

#### Screenshot or Gif（截图或动态图）
error

image

#### Link to minimal reproduction（最小可在线还原demo）
https://demo-ui.erpya.com/

#### Expected behavior

Error does not load the panel with the fields. This case only happens with windows since in the process and smart browser it works

#### Other relevant information
- Your OS: Debina 9
- Web Browser: Chrome
- Node.js version: v 14.18.0
- adempiere-vue version: v 4.4.0

### PR DESCRIPTION
**Pull request by elsiosanchez**
## Bug report
Fix Load panel and fields in window

Error does not load the panel with the fields. This case only happens with windows since in the process and smart browser it works
#### Steps to reproduce

1. start section
2. there will be any window

#### Screenshot or Gif（截图或动态图）
success

#### Link to minimal reproduction（最小可在线还原demo）
https://demo-ui.erpya.com/

#### Expected behavior

Error does not load the panel with the fields. This case only happens with windows since in the process and smart browser it works

#### Other relevant information
- Your OS: Debian 9
- Web Browser: Chrome
- Node.js version: v 14.18.0
- Yarn version: v 1.22.0
- adempiere-vue version: v 4.4.0

#### Issues
Fixed #1681

### CODE REVIEW

File: src/components/ADempiere/PanelDefinition/index.vue [hunk 1]
```diff
@@ -42,6 +42,10 @@ export default defineComponent({
       type: String,
       required: true
     },
+    panelMetadata: {
```
Comment (EdwinBetanc0urt) [inline src/components/ADempiere/PanelDefinition/index.vue]: Panel metadata as prop is unnecessary, use the `containerManager.getPanel({ parentUuid, containerUuid })` method.

**Review by EdwinBetanc0urt — CHANGES_REQUESTED** [review]

File: src/components/ADempiere/PanelDefinition/index.vue (hunk 1 above)
Comment (elsiosanchez) [reply src/components/ADempiere/PanelDefinition/index.vue]: Greetings @EdwinBetanc0urt The error that was throwing when one opens a window were the following
1. That it was not sending the `parentUuid` in the `props.containerManager.getPanel` method, so the method was returning a undefine and instead it was loading the `panelMetadata`.

2. That in case this condition `if (props.containerManager && props.containerManager.getPanel)` that you put was not fulfilled you were sending to the `props.panelMetadata` so the `panelMetadata` property as it is not registered in the properties the `getPanel()` did not paint the fields and threw an error.

Comment (elsiosanchez) [reply src/components/ADempiere/PanelDefinition/index.vue]: Greetings @EdwinBetanc0urt The error that was throwing when one opens a window were the following
1. That it was not sending the `parentUuid` in the `props.containerManager.getPanel` method, so the method was returning a undefine and instead it was loading the `panelMetadata`.

2. That in case this condition `if (props.containerManager && props.containerManager.getPanel)` that you put was not fulfilled you were sending to the `props.panelMetadata` so the `panelMetadata` property as it is not registered in the properties the `getPanel()` did not paint the fields and threw an error.
