### PR TITLE
fix 404

### LINKED ISSUE #617: [Bug Report] 404 when I trying open a perm link
## Bug report
I want to open a perm link line this: https://demo-ui.erpya.com/#/f855ca25-07b2-4760-aec6-676db1a5cb19/d97027fd-4cd5-445e-8fd8-ef5d3f7959b4/window/366?tabParent=0&tabChild=0

#### Steps to reproduce

1. Open the follow URL: https://demo-ui.erpya.com/#/f855ca25-07b2-4760-aec6-676db1a5cb19/d97027fd-4cd5-445e-8fd8-ef5d3f7959b4/window/366?tabParent=0&tabChild=0
2. Login with SuperUser
3. See the page

#### Screenshot or Gif（截图或动态图）

Screenshot_2021-03-01-20-46-09-262_com android chrome

#### Other relevant information
- Your OS: Android
- Web Browser: Google Chrome
- Node.js version:
- adempiere-vue version:

### PR DESCRIPTION
**Pull request by elsiosanchez**
## Bug report / Feature
I want to open a perm link line this: http://localhost:9527/#/7aa4242a-93c0-42d8-92be-8250002d3e3c/d97027fd-4cd5-445e-8fd8-ef5d3f7959b4/process/54567

#### Steps to reproduce

1. Open the follow URL: http://localhost:9527/#/7aa4242a-93c0-42d8-92be-8250002d3e3c/d97027fd-4cd5-445e-8fd8-ef5d3f7959b4/process/54567
2. Login with SuperUser
3. See the page

### Screenshot or Gif

https://user-images.githubusercontent.com/45974454/110392681-b56c4a00-803f-11eb-817d-7ba9aa96f064.mp4

#### Link to minimal reproduction

http://localhost:9527/#/7aa4242a-93c0-42d8-92be-8250002d3e3c/d97027fd-4cd5-445e-8fd8-ef5d3f7959b4/process/54567

#### Other relevant information
- Your OS: Debian 9
- Web Browser: Chrome
- Node.js version: 10.19.0

fixes: #617

### CODE REVIEW

File: src/store/modules/permission.js [hunk 1]
```diff
@@ -28,16 +28,26 @@ const actions = {
...
       const role = rootGetters['user/getRole']
       let roleUuid
+      console.log({
+        roleUuid
+      })
       if (!isEmptyValue(role)) {
         roleUuid = role.uuid
       }
-
+      console.log({
```
Comment (yamelsenih) [inline src/store/modules/permission.js]: Please remove unnecessary log

File: src/store/modules/permission.js [hunk 2]
```diff
@@ -28,16 +28,26 @@ const actions = {
...
       const organization = rootGetters['user/getOrganization']
       let organizationUuid
+      console.log({
+        organizationUuid
+      })
       if (!isEmptyValue(organization)) {
         organizationUuid = organization.uuid
       }
-
+      console.log({
```
Comment (yamelsenih) [inline src/store/modules/permission.js]: Please remove unnecessary log

File: src/store/modules/permission.js [hunk 3]
```diff
@@ -28,16 +28,26 @@ const actions = {
     return new Promise(resolve => {
       const organization = rootGetters['user/getOrganization']
       let organizationUuid
+      console.log({
+        organizationUuid
```
Comment (yamelsenih) [inline src/store/modules/permission.js]: Please remove unnecessary log

**Review by yamelsenih — CHANGES_REQUESTED** [review]
Please remove unnecessary log
